apiVersion: v1
data:
  DEBUG: "1"
  SECRET_KEY: "foo"
  DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1] balancertestsite.com"
  SQL_ENGINE: "django.db.backends.postgresql"
  SQL_DATABASE: "balancer_dev"
  SQL_USER: "balancer"
  SQL_PASSWORD: ""
  SQL_HOST: ""
  SQL_PORT: "5432"
  DATABASE: "postgres"
  LOGIN_REDIRECT_URL: ""
  OPENAI_API_KEY: ""
  PINECONE_API_KEY: ""
  REACT_APP_API_BASE_URL: "https://balancertestsite.com/"
kind: ConfigMap
metadata:
  name: balancer-config
