apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balancer
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - balancertestsite.com
      secretName: balancer-tls
  rules:
    - host: balancertestsite.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: balancer
                port:
                  number: 80
