name: balancer
description: The helm chart for the balancer project
version: 0.1.0
apiVersion: v2
sources:
  - https://github.com/CodeForPhilly/balancer-main
home: https://opencollective.com/code-for-philly/projects/balancer
