nameOverride: ""
fullnameOverride: ""

backend:
  replicaCount: 1
  image:
    repository: balancer-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1024m
      memory: 3Gi
  config:
    debug: "1"
    allowedHosts: "*"

frontend:
  replicaCount: 1
  image:
    repository: balancer-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  secrets:
    apiKey: ""  # Example encrypted value

# Database configuration
database:
  # Set to true to use the internal PostgreSQL database
  # Set to false to use an external database
  internal: true
  # External database configuration (used when internal: false)
  host: "your-external-db-host.com"
  port: "5432"
  # Common database configuration (used for both internal and external)
  image:
    repository: postgres
    tag: "14"
    pullPolicy: IfNotPresent
  user: balancer
  name: balancer_dev
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: ""  # Use default storage class if not specified

email:
  hostUser: balancer-noreply@codeforphilly.org