apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: balancer

resources:
  - ../../base

images:
  - name: ghcr.io/codeforphilly/balancer-main/app
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: balancer
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
      - op: replace
        path: /spec/tls/0/hosts/0
        value: localhost
      - op: replace
        path: /spec/rules/0/host
        value: localhost
