apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-balancer-secrets
  labels:
    {{- include "balancer.labels" . | nindent 4 }}
spec:
  encryptedData:
    secret-key: {{ .Values.sealedSecrets.secretKey | quote }}
    email-password: {{ .Values.sealedSecrets.emailPassword | quote }}
    database-password: {{ .Values.sealedSecrets.databasePassword | quote }}
    openai-api-key: {{ .Values.sealedSecrets.openaiApiKey | quote }}
  template:
    metadata:
      labels:
        {{- include "balancer.labels" . | nindent 8 }}
    type: Opaque 