apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "balancer.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.secrets.secretKey | b64enc }}
  email-password: {{ .Values.secrets.emailPassword | b64enc }}
  database-password: {{ .Values.secrets.databasePassword | b64enc }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc }} 