{{- if .Values.backend.secrets.useExternalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  labels:
    {{- include "balancer.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.backend.secrets.externalSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-backend-secrets
    template:
      metadata:
        labels:
          {{- include "balancer.labels" . | nindent 10 }}
          app.kubernetes.io/component: backend
  data:
    - secretKey: secret-key
      remoteRef:
        key: {{ .Values.backend.secrets.externalSecretPath }}/secret-key
    - secretKey: email-password
      remoteRef:
        key: {{ .Values.backend.secrets.externalSecretPath }}/email-password
    - secretKey: database-password
      remoteRef:
        key: {{ .Values.backend.secrets.externalSecretPath }}/database-password
    - secretKey: openai-api-key
      remoteRef:
        key: {{ .Values.backend.secrets.externalSecretPath }}/openai-api-key
{{- end }} 